server:
  port: 8081
spring:
  datasource:
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/emp
    type: com.alibaba.druid.pool.DruidDataSource
